version: '3'

services:
  # database:
  #   image: postgres:11.1-alpine
  #   volumes:
  #     - ./database:/var/lib/pgsql/
  #   environment:
  #     - POSTGRES_DB=${DATABASE_NAME}
  #     - POSTGRES_USER=${DATABASE_USER}
  #     - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
  #   expose:
  #     - 5432

  database:
    image: mysql:5.7
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    expose:
      - 3306

  php-fpm:
    build:
      context: ./php-fpm
    depends_on:
      - database
    environment:
      - GIT_REPO_URL=${GIT_REPO_URL}
      - GIT_REPO_BRANCH=${GIT_REPO_BRANCH}
      - COMPOSER_VERSION=${COMPOSER_VERSION}      
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}
      - MAILER_URL=${MAILER_URL}
      - ADMIN_EMAIL_ADDRESS=${ADMIN_EMAIL_ADDRESS}
      - LOCALE=${LOCALE}
    volumes:
      - web:/var/www
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./php-fpm/entrypoint.sh:/root/entrypoint.sh   
    entrypoint: /root/entrypoint.sh
    expose:
      - 9000

  nginx:
    image: nginx:alpine
    volumes:
      - web:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    ports:
      - "${APP_PORT}:80"


volumes:
    web:
    database:

# networks:

